correction of the dependence of the rn test

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -23,7 +23,18 @@ jobs:
       - name: Run coding style check
         run: check.sh $(pwd) $(pwd)
       - name: Display coding style report
-        run: cat $(pwd)/coding-style-reports.log
+        run:  |
+          CODING_STYLE_ERROR=$(pwd)/coding-style-reports.log
+          for ERRORS in $CODING_STYLE_ERROR; do
+              array=(echo $ERRORS | sed 's/:/\n/g')
+              echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
+          done
+          if[[-n $CODING_STYLE_ERRORS]]
+          then
+            exit 1
+          else
+            echo No coding style errors detected
+          fi
 
   check_program_compilation:
     needs: [check_coding_style]
@@ -36,7 +47,14 @@ jobs:
       - name: test_compilation
         run: make
       - name: test_other
-        run: make clean
+        run: |
+           OIFS = $IFS
+           IFS=','
+           for x in $EXECUTABLES
+              do
+               ./$x $ARGUMENTS
+              done
+            IFS=$OIFS
 
   run_tests:
     needs: [check_program_compilation]
